name: EAS Build

on:
  workflow_dispatch:
    inputs:
      profile:
        description: "Profile"
        type: choice
        default: simulator
        required: true
        options:
          - simulator
          - development
          - preview
          - production
      submit:
        description: "Submit to App Store"
        type: boolean
        required: true
        default: false

jobs:
  update:
    name: EAS Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          packager: bun
          token: ${{ secrets.EXPO_TOKEN }}
      - name: 📢 EAS Build
        run: eas build -e ${{ inputs.profile }} -p ios --non-interactive --no-wait
        working-directory: ./apps/app
        if: ${{ inputs.profile == 'simulator' || inputs.profile == 'development' || !inputs.submit }}
      - name: 📢 EAS Build and Submit
        run: eas build -e ${{ inputs.profile }} -p ios --non-interactive --no-wait --auto-submit
        working-directory: ./apps/app
        if: ${{ inputs.submit && inputs.profile == 'production' }}
