name: Web Production

on: workflow_dispatch

jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: web-production
      url: ${{ steps.cloudflare-publish.outputs.url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Build web
        run: bun run build
        working-directory: apps/web
      - name: Publish to Cloudflare Pages
        id: cloudflare-publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: sharemystack-web
          directory: public
          workingDirectory: apps/web
          wranglerVersion: 3
